services:
  - type: web
    name: salon-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:app
    envVars:
      - key: BOT_TOKEN
        value: 8242692690:AAExQ8RcUrSprRLX4-QCQAQxxTSiXaxNxP4